baseURL = "https://blog.rmendes.net"
title = "rMdes Blog"
copyright = "Copyright © 2023, Copyright Ricardo Mendes"
languageCode = "en-US"
theme = "indigo"
canonifyurls  = true
#contentdir    = "content"
#layoutdir     = "layouts"
#publishdir    = "public"

[params]
  Author = "Ricardo Mendes"
  Description = "Just my blog on the internet"
  Subtitle = "a place to write and think"
  Avatar = "images/site-logo.svg"
  Biography = "Geek sur la Tech, l'information, la démocratie, la Justice et le discernement | Partie civile OKCinfo"
  ShowBio = true
  PermalinkText = "Link"
  #mainSections = ["post", "updates"]
  # Web Monetization only works on secure pages served over HTTPS.
  paymentPointer = ""

  # Contact/social-network identifiers for social icons
  EmailAddress = "info@rmendes.net"
  GitHubUser = "rmdes"
  GitLabUser = "rmdes"
  KeybaseUser = "rmendes"
  LinkedInUser = "mendesr"
  TwitterUser = "rmdes_"

  # These are parameters used for indieweb identity. You should set these along
  # with the above email/social network parameters.
  [params.indieWeb]  
    EmailAddress = "info@rmendes.net"
    GitHubUser = "rmdes"
    TwitterUser = "rmdes_"
    Country = "Belgium"
    City = "Brussels"

  [params.endpoints]
    Auth = "https://indieauth.com/auth"
    Token = "https://tokens.indieauth.com/token"
    # To get webmention support, just register at webmention.io and paste the link for endpoint here.
    Webmention = "https://webmention.io/blog.rmendes.net/webmention"
    # To get micropub support, you'll need to install a Micropub endpoint at your site and put its link there.
    # To get an endpoint with Hugo support, use nanopub: https://github.com/dg01d/nanopub
    # It will probably require some PHP hackery though, as it's fairly basic.
    #Micropub = ""
    # To get microsub support, you can use Aperture from p3k. Either go to https://aperture.p3k.io or self-host it (it's open source!)
    #Microsub = ""

[[menu.main]]
    name = "About"
    url = "about"
    weight = 1

[[menu.main]]
    identifier = "Archive"
    name = "archive"
    weight = 2

[[menu.main]]
    name = "Replies"
    url = "replies"
    weight = 3

[[menu.main]]
    name = "Tweets"
    url = "tweets"
    weight = 4
    
[[menu.main]]
    name = "Bookmarks"
    url = "bookmarks"
    weight = 5
    
[[menu.main]]
    name = "Reading Now"
    url = "books"
    weight = 6

[[menu.main]]
    name = "Finished Readings"
    url = "finished-reading"
    weight = 7

[[menu.main]]
    name = "Want to Read"
    url = "want-to-read"
    weight = 8
    
[[menu.main]]
    name = "Search"
    url = "search"
    weight = 9
    
[[menu.main]]
    name = "Feeds"
    url = "feeds"
    weight = 10
    
 
